### ISSUE TITLE
Capture problem

### ISSUE THREAD

**Issue by kozaksv** [upday7/WebQuery#12]
I use MacBook Pro Retina.

Before capturing
![image](https://user-images.githubusercontent.com/776308/38389454-2a0bc7ea-3927-11e8-8efd-e70105b5656d.png)

the page move to the right and become much bigger When I'm trying to capture something 
![image](https://user-images.githubusercontent.com/776308/38389485-4837e5a0-3927-11e8-8cc3-640468e7339e.png)

**Comment by upday7** [comment]
fixed for anki2.1

**Comment by kozaksv** [comment]
The problem remains. 

![2018-04-26_14-42-07](https://user-images.githubusercontent.com/776308/39303852-5ca0bc8a-4960-11e8-8a89-587298fff4f4.gif)
